config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from root.sitemap import StaticViewSitemap, DynamicViewSitemap, StaticViewSitemap2

sitemaps = {
    "static" : StaticViewSitemap,
    "dynamic" : DynamicViewSitemap,
    "static2" : StaticViewSitemap2,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("root.urls")),
    path("services/", include("services.urls")),
    path("accounts/", include("accounts.urls")),
    path('robots.txt', include('robots.urls')),
    path(
    "sitemap.xml",
    sitemap,
    {"sitemaps": sitemaps},
    name="django.contrib.sitemaps.views.sitemap",
)
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

root/urls.py
from django.http import HttpResponse

from django.urls import path
from .views import *

app_name = 'root'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contactus/', contact, name='contact'),
    path('about/', AboutView.as_view(), name='about'),
]

services/urls.py
from django.urls import path
from .views import *
from django.views.generic import RedirectView


app_name = 'services'

urlpatterns = [
    path('', ServiceView.as_view(), name='services'),
    path('category/<str:category>', ServiceView.as_view(), name='list_by_category'),
    path('price/<int:price>', ServiceView.as_view(), name='list_by_price'),
    #path('service-detail/<int:pk>', services_detail, name='services-detail'),
    path('service-detail/<int:pk>', ServiceDetaiView.as_view(), name='services-detail'),
    path('qoute/', qoute, name='qoute'),
    path("comment/edit/<int:id>", edit_comment, name='edit_comment'),
    path("adv", GoogleView.as_view(), name='adv1'),
]

services/models.py
from django.db import models
from django.contrib.auth import get_user_model
from accounts.models import Profile
User = get_user_model()




class SpecialService(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)

    class Meta:
        ordering =['-created_at']


    def __str__(self):
        return self.title
    
class Skills(models.Model):
    title = models.CharField(max_length=100)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

class Team(models.Model):
    image = models.ImageField(upload_to='services', default='default.jpg')
    profile = models.ForeignKey(User, on_delete=models.CASCADE)
    skills = models.ManyToManyField(Skills)
    description = models.TextField()
    status = models.BooleanField(default=False)
    facebook = models.CharField(max_length=220, default="#")
    twitter = models.CharField(max_length=220, default="#")
    instagram = models.CharField(max_length=220, default="#")
    linkdin = models.CharField(max_length=220, default="#")



    def __str__(self):
        return self.profile.email
    

    def truncate_char(self):
        return str(self.description)[:10]

class Category(models.Model):
    title = models.CharField(max_length=100)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

class Options(models.Model):
    title = models.CharField(max_length=300)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title
    

class Services(models.Model):
    image = models.ImageField(upload_to='services', default='image.jpg')
    name = models.CharField(max_length=300)
    content = models.TextField()
    title = models.CharField(max_length=300)
    description = models.TextField()
    category = models.ManyToManyField(Category)
    generals = models.ManyToManyField(Options)
    status = models.BooleanField(default=True)
    price = models.IntegerField()
    counted_view = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name
    

class Comments(models.Model):
    product_name = models.CharField(max_length=100)
    message = models.TextField()
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product_name
    

services/forms.py
from django import forms
from .models import Comments


class CommentsForm(forms.ModelForm):

    class Meta:
        model = Comments
        fields = ('product_name', 'message')

services/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentsForm
from django.contrib import messages
from django.views.generic import ListView, DetailView, RedirectView

# Create your views here.



class ServiceView(ListView):
    template_name = 'services/services.html'
    context_object_name = 'services'
    # queryset = Services.objects.filter(status=True)
    #paginate_by = 2

    def get_queryset(self):

        if self.kwargs.get ('category'):
            all_service = Services.objects.filter(category__title=self.kwargs.get('category'))
        else:
            all_service = Services.objects.filter(status=True)
        
        return all_service



class GoogleView(RedirectView):
    url = "https://google.com"

class ServiceDetaiView(DetailView):
    model = Services
    template_name = 'services/service-details.html'
    context_object_name = 'detail'


    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        service = Services.objects.get(pk=self.kwargs.get("pk"))
        commnets = Comments.objects.filter(product_name=service.name, status=True)
        context ['comments'] = commnets
        return context


# def services(request, **kwargs):
# #    if request.GET.get('category') is not None:
# #        all_service = Services.objects.filter(category__title=request.GET.get('category'))
#     if kwargs.get('category'):
#         all_service = Services.objects.filter(category__title=kwargs.get('category'))

        
#     elif request.GET.get('search') is not None:
#         all_service = Services.objects.filter(content__contains=request.GET.get('search'))

# #    elif price:
# #        all_service = Services.objects.filter(price__lte=price)
#     elif kwargs.get('price'):
#         all_service = Services.objects.filter(price__lte=kwargs.get('price'))

#     else:
#         all_service = Services.objects.filter(status=True)

#     all_services = Paginator(all_service,2)
#     last_page = all_services.num_pages
#     try:
#         page_number = request.GET.get('page')
#         all_services = all_services.get_page(page_number)
#     except PageNotAnInteger:
#         all_services = all_services.get_page(1)
#     except EmptyPage:
#          all_services = all_services.get_page(1)
#Comments.objects.filter(product_name=service.name, status=True)
#             "specials": SpecialService.objects.filter(status=True),
#             'last_page': last_page,
#         }
#     return render(request, 'services/services.html', context = context)



# def services_detail(request, id):
#     #service = Services.objects.get(id=id)

#     #service = get_object_or_404(Services, id=id)

#     try:
#         service = Services.objects.get(id=id)
#         comments = Comments.objects.filter(product_name=service.name, status=True)
#         service.counted_view += 1
#         service.save()
#         context = {
#             'detail':service,
#             'comments': comments,
#         }
#         return render(request, 'services/service-details.html', context = context)
    
#     except:
#         return render(request, 'services/404.html')


def qoute(request):
    if request.method == 'POST':
        #if request.user.is_authenticated:
            form = CommentsForm(request.POST)
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.SUCCESS, 'your comments was delivered successfully and will be published ASAP !...')
                return redirect(request.path_info)
            else:
                messages.add_message(request, messages.ERROR, 'your input data may be incorrect')
                return redirect(request.path_info)
        # else:
        #     return redirect('accounts:login')
    else:
        return render(request, 'services/get-a-quote.html')
    
def edit_comment(request, id):
    comment = get_object_or_404(Comments, id=id)
    if request.method == 'POST':
        form = CommentsForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
#            obj = form.save(commit=False)
#            obj.status = False
#            obj.save()
            return redirect("services:services")
    else:
        form = CommentsForm(instance=comment)
        context = {
            'form': form,
        }
        return render (request, 'services/edit.html', context=context)

templates/services/edit.html
<form method="post">
    {% csrf_token %}
{% comment %}     <input type="text" value={{comment.message}}> {% endcomment %}
    {{form}}
    <button type="submit" class="btn btn-primary">edit_comments</button>
</form>

templates/services/get-a-quote.html
{% extends "base.html" %}
{% load static %}
{% block 'title' %}get-a-quote{% endblock 'title' %}
{% block 'content' %}
  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="page-header d-flex align-items-center" style="background-image: url(""{% static 'assets/img/page-header.jpg' %});">
        <div class="container position-relative">
          <div class="row d-flex justify-content-center">
            <div class="col-lg-6 text-center">
              <h2>Get a Quote</h2>
              <p>Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat ipsum dolorem.</p>
            </div>
          </div>
        </div>
      </div>
      <nav>
        <div class="container">
          <ol>
            <li><a href="index.html">Home</a></li>
            <li>Get a Quote</li>
          </ol>
        </div>
      </nav>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Get a Quote Section ======= -->
    <section id="get-a-quote" class="get-a-quote">
      <div class="container" data-aos="fade-up">

        <div class="row g-0">

          <div class="col-lg-5 quote-bg" style="background-image: url({% static 'assets/img/quote-bg.jpg' %});"></div>

          <div class="col-lg-7">
            <form method="post">
              {% csrf_token %}
              <h3>Get a quote</h3>
              <p>Vel nobis odio laboriosam et hic voluptatem. Inventore vitae totam. Rerum repellendus enim linead sero park flows.</p>
              <div class="row gy-4">

                <div class="col-md-6">
                  <input type="text" name="product_name" class="form-control" placeholder="Product or service" required>
                </div>

                <div class="col-md-12">
                  <textarea class="form-control" name="message" rows="6" placeholder="Message" required></textarea>
                </div>

                  <button type="submit">Get a quote</button>
                </div>

              </div>
            </form>
            {% if messages %}
            {% for message in messages %}
                {{message}}
            {% endfor %}
            {% endif %}
          </div><!-- End Quote Form -->

        </div>

      </div>
    </section><!-- End Get a Quote Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-4">
        <div class="col-lg-5 col-md-12 footer-info">
          <a href="index.html" class="logo d-flex align-items-center">
            <span>Logis</span>
          </a>
          <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
          <div class="social-links d-flex mt-4">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About us</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Terms of service</a></li>
            <li><a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><a href="#">Web Design</a></li>
            <li><a href="#">Web Development</a></li>
            <li><a href="#">Product Management</a></li>
            <li><a href="#">Marketing</a></li>
            <li><a href="#">Graphic Design</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
          <h4>Contact Us</h4>
          <p>
            A108 Adam Street <br>
            New York, NY 535022<br>
            United States <br><br>
            <strong>Phone:</strong> +1 5589 55488 55<br>
            <strong>Email:</strong> info@example.com<br>
          </p>

        </div>

      </div>
    </div>

    <div class="container mt-4">
      <div class="copyright">
        &copy; Copyright <strong><span>Logis</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/logis-bootstrap-logistics-website-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>

{% endblock 'content' %}

templates/services/service-details.html
{% extends "base.html" %}
{% load static %}
{% block 'title' %}services-detail{% endblock 'title' %}
{% block 'content' %}

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="page-header d-flex align-items-center" style="background-image: url('{% static 'assets/img/page-header.jpg' %}');">
        <div class="container position-relative">
          <div class="row d-flex justify-content-center">
            <div class="col-lg-6 text-center">
              <h2>Service Details</h2>
              <p>Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat ipsum dolorem.</p>
            </div>
          </div>
        </div>
      </div>
      <nav>
        <div class="container">
          <ol>
            <li><a href="index.html">Home</a></li>
            <li>Service Details</li>
          </ol>
        </div>
      </nav>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Service Details Section ======= -->
    <section id="service-details" class="service-details">
      <div class="container" data-aos="fade-up">

        <div class="row gy-4">

          <div class="col-lg-4">
            <div class="services-list">
                {% for obj in detail.category.all %}
              <a href="#">{{obj.title}}</a>
              {% endfor %}

            </div>

            <h4>{{detail.name}}</h4>
            <p>{{detail.content}}</p>
          </div>

          <div class="col-lg-8">
            <img src={{detail.image.url}} alt="" class="img-fluid services-img">
            <h3>{{detail.title}}</h3>
            <p>
              {{detail.description}}
            </p>
            <ul>
              {% for obj in detail.generals.all %}
              <li><i class="bi bi-check-circle"></i> <span>{{obj.title}}</span></li>
              {% endfor %}
            </ul>
            <p>
              {{detail.price}}
            </p>
            <p>
              {{detail.counted_view}}
            </p>
          </div>

        </div>
        {% for comment in comments %}
           <p><a href={% url "services:edit_comment"  id=comment.id %}>{{comment.message}}</p>
        {% endfor %}

      </div>
    </section><!-- End Service Details Section -->

  </main><!-- End #main -->

  <a href={% url 'services:adv1' %}>advertise</a>

  <!-- ======= Footer ======= -->
  {% endblock 'content' %}